project:
  type: website

website:
  title: "Lizbeth Amador, M.S. Ecology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: scicomm.qmd
        text: Outreach and Engagement
      - href: dei.qmd
        text: JDEI
      - href: cv.qmd
        text: CV
      - href: portfolio.qmd
        text: Portfolio
    tools: 
    - icon: linkedin
      text: LinkedIn
      href: www.linkedin.com/in/lizbeth-amador-935412280
    # - favicon: path/icon.svg #icon for website tab 
    - favicon: ./images/orcid_reversed.png
      text: ORCID
      href: https://orcid.org/0009-0002-7238-1247 
    - icon: github
      text: Github
      href: https://github.com/lgamador
    - icon: envelope-at
      text: Email
      href: mailto::lamador0213@gmail.com
  page-footer: 
    background: dark

format:
  html: 
    theme:
      - flatly
    css: styles.css
    toc: true


